spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3307/teamplayerdevdb
    username: root
    password: root
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyJpaCompliantImpl
    properties:
      hibernate:
        globally_quoted_identifiers: true
        dialect: org.hibernate.dialect.MySQL5Dialect
  application:
    name: team-player
  profiles:
    active: dev
server:
  port: 8090
jwt:
  secret: JWTSuperSecretKey
  signToken: Authorization
  jwtExpirationInMs: 604800000